name: dart_firebase_functions
description: Enables Dart developers to define HTTP and Cloud Firestore triggered functions, providing Node.js-like Firebase functions capability.
version: 0.0.1-dev.1
homepage: https://github.com/kosukesaigusa/dart_firebase_functions

environment:
  sdk: ^3.2.5

dependencies:
  dart_firebase_admin: ^0.3.0
  fixnum: ^1.1.0
  functions_framework: ^0.4.3+1
  protobuf: ^3.1.0

dev_dependencies:
  test: ^1.24.0
