name: dart_firebase_functions
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.5

dependencies:
  dart_firebase_admin: ^0.3.0
  functions_framework: ^0.4.3+1
  protobuf: ^3.1.0

dev_dependencies:
  test: ^1.24.0
