name: dart_firebase_functions_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.5

dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build: ^2.0.0
  build_config: '>=0.4.3 <2.0.0'
  dart_firebase_functions:
  dart_style: ^2.0.0
  functions_framework: ^0.4.3+1
  meta: ^1.2.4
  path: ^1.9.0
  source_gen: ^1.0.0

dev_dependencies:
  test: ^1.15.7