name: server
description: A starting point for Dart libraries or applications.
publish_to: 'none'

environment:
  # Required for dart_firebase_admin >=0.2.0
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dart_firebase_admin: ^0.3.0
  dart_firebase_functions: ^0.0.1-dev.1
  functions_framework: ^0.4.0
  http: ^1.0.0
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  dart_firebase_functions_builder: ^0.0.1-dev.1
  test: ^1.15.7
