services:
  - service: hello
    signature_type: http
  - service: oncreatetodo
    signature_type: cloudevent
    event_type: google.cloud.firestore.document.v1.created
    path_pattern: document=todos/{todoId}
  # - service: onupdatetodo
  #   signature_type: cloudevent
  #   event_type: google.cloud.firestore.document.v1.updated
  #   path_pattern: document=todos/{todoId}
  # - service: ondeletetodo
  #   signature_type: cloudevent
  #   event_type: google.cloud.firestore.document.v1.deleted
  #   path_pattern: document=todos/{todoId}
  # - service: onwritetodo
  #   signature_type: cloudevent
  #   event_type: google.cloud.firestore.document.v1.written
  #   path_pattern: document=todos/{todoId}
  - service: oncreatesubmission
    signature_type: cloudevent
    event_type: google.cloud.firestore.document.v1.created
    path_pattern: document=submissions/{submissionId}
  - service: createfirebaseauthcustomtoken
    signature_type: http
