name: client
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter:
    sdk: flutter
  flutter_line_sdk: ^2.3.6
  flutter_riverpod: ^2.4.9
  flutterfire_gen_annotation: ^0.4.1
  flutterfire_gen_utils: ^0.4.1
  http: ^1.0.0
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  flutterfire_gen: ^0.4.3
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
